# Generated by Django 5.2.8 on 2025-12-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcardprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardset',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
