# Generated by Django 5.2.8 on 2026-01-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_flashcardprogress_predefined_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardprogress',
            name='session_key',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='flashcardprogress',
            constraint=models.UniqueConstraint(fields=('session_key', 'set'), name='uniq_progress_session_set'),
        ),
        migrations.AddConstraint(
            model_name='flashcardprogress',
            constraint=models.UniqueConstraint(fields=('session_key', 'predefined_key'), name='uniq_progress_session_predef'),
        ),
    ]
